#!/usr/bin/env python3
"""Agent 6: Script — writes the full script section by section."""

from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from agents.lib.agent_base import AgentBase
from shadow_protocol.lib.file_utils import write_text, read_json


class ScriptAgent(AgentBase):
    name = "script"

    def run(self) -> int:
        outline_path = self.input_dir / "outline.json"
        if not outline_path.exists():
            return self.fail("OUTLINE_NOT_FOUND", "outline.json is required")

        outline = read_json(outline_path)
        acts = outline.get("acts", [])

        for act in acts:
            for scene in act.get("scenes", []):
                section = self._write_section(act, scene)
                section_n = scene.get("scene", 1)
                out_path = self.output_dir / f"script_section_{section_n}.md"
                write_text(out_path, section)
                print(f"[Script] Written {out_path}")

        print(f"[Script] All sections complete.")
        return 0

    def _write_section(self, act: dict, scene: dict) -> str:
        return (
            f"# Script — Act {act.get('act')} Scene {scene.get('scene')}\n\n"
            f"**Scene:** {scene.get('summary', '')}\n\n"
            f"[Full script content to be generated by LLM]\n"
        )


def run(input_dir: str, output_dir: str, config: dict) -> int:
    agent = ScriptAgent(input_dir, output_dir, config)
    return agent.run()


if __name__ == "__main__":
    import json
    _, input_dir, output_dir, config_path = sys.argv
    config = json.load(open(config_path))
    sys.exit(run(input_dir, output_dir, config))
