#!/usr/bin/env python3
"""Agent 3: Story Idea — generates a high-concept episode pitch."""

from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from agents.lib.agent_base import AgentBase
from shadow_protocol.lib.file_utils import write_text


class StoryIdeaAgent(AgentBase):
    name = "story_idea"

    def run(self) -> int:
        print(f"[StoryIdea] Generating story idea...")
        content = self._generate_pitch()
        out_path = self.output_dir / "story_idea.md"
        write_text(out_path, content)
        print(f"[StoryIdea] Written to {out_path}")
        return 0

    def _generate_pitch(self) -> str:
        return (
            f"# Story Idea\n\n"
            f"Episode: {self.input_dir.name}\n\n"
            f"## Logline\n"
            f"A protagonist whose reality collapses uncovers a hidden system of power.\n\n"
            f"## Synopsis\n"
            f"[To be generated by LLM in Phase 1]\n"
        )


def run(input_dir: str, output_dir: str, config: dict) -> int:
    agent = StoryIdeaAgent(input_dir, output_dir, config)
    return agent.run()


if __name__ == "__main__":
    import json
    _, input_dir, output_dir, config_path = sys.argv
    config = json.load(open(config_path))
    sys.exit(run(input_dir, output_dir, config))
